### ISSUE TITLE
Plugin 'libsteam_api.so' is used from several locations

### ISSUE THREAD

**Issue by shosanna** [rlabrecque/Steamworks.NET#402]
Hey,
I am trying to upgrade to a newer version of the library, as I was suddenly having this problem https://github.com/rlabrecque/Steamworks.NET/issues/350 (except for me all the issues are happening in Mac) and I am unable to do so.

I first tried to upgrade - download from the master branch and replace the files in `Assets`, specifically everything under `Editor` and `Plugins`. I was having a issue saying that `steam_api.bundle` is damaged and should be moved to bin. 

After unsuccessfully trying to work it out for some time and headache, I decided to completely remove everything from Steamworks from my game and then reinstall it from scratch. I deleted manually:
- Assets/Editor
- Assets/Plugins/Steamworks.NET
- Assets/Plugins/steam_api.bundle
- Assets/Plugins/x86_64
- Assets/Plugins/x86

I mean I deleted everything from those folders and even the metafiles. 
Then I downloaded master and added Editor and content of Plugins under Assets. I also tried to download the last release (even though that is behind the master) and import it via Unity importer, I tried both approaches separately but got the same issue.

When I am building the mac build, I get this error:

```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

My guess is I did not deleted everything and I somehow still have multiple versions? 
I am quite desperate as I do not know how to make it work, how to completely remove it, upgrade, install... nothing ..

I would appreciate any help or advice on how to proceed to just make it work with the newest version .. Thanks!

P.S. my Unity version: 2020.2.3f1

**Comment by rlabrecque** [comment]
Hey @shosanna, if you aren't shipping your game on Linux you can freely just delete the libsteam_api.so files. If you are shipping on Linux, or just want to keep those files, then you need to change the import settings on those files specifically now with 2020.2. I'm working to ship the meta files required to fix this for Unity 2020.2, but it may be a bit before that happens

This thread is somewhat related: https://github.com/rlabrecque/Steamworks.NET/issues/393

**Comment by shosanna** [comment]
@rlabrecque hey thanks for your answer! I deleted the extra files but the build is still crashing just after start, here is the part of the logs:

```
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (Steamworks.AppId_t unOwnAppID) [0x00005] in <8464b6072cc34b8f8d4d4e0062e4f123>:0 
  at SteamManager.Awake () [0x00061] in <05ae5849c8ff44ef84bb1994cc67ccb2>:0 
```

Any idea why it is on a different location than it should be? I am sorry, maybe I am doing something obvious wrongly, I do not understand those things at all :/

**Comment by shosanna** [comment]
@rlabrecque so we actually made it work, thanks for your help anyway! It turned out to be a problem with me building it on my M1 macbook - after I did an Intel mac build (and run it on Macbook with Rosetta), it all worked ...

**Comment by RobDonovan** [comment]
I'm also getting this error.

I was on Unity 2018.4 and version 1.46 of Steamworks.NET

Just upgraded to 2019.4 and version 1.50 of Steamworks.NET

I compile for Windows 64, Linux 64 and Mac Universal, through the Unity cloud build.

Everything is ok for Win and Linux, but Mac build fails with:
13415: [Unity] ERROR: Plugin 'libsteam_api.so' is used from several locations:
13416: [Unity]  Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
13417: [Unity]  Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
13418: [Unity] Please fix plugin settings and try again.

Now, plugins are new to me, and I dont fully understand them yet.

I'm not sure why Unity is trying to copy the libsteam_api.so files for the Mac build. The settings are as the default and is currently set to not be for 'Max OS X' on the x86 version, but it IS included for the x86_64 version. Not sure why the x86_64 version is set for Mac, I thought it would only need the 'libsteam_api.dylib from the bundle folder.

As suggested in the other thread, it looks like there is a Unity error, with the x86 version and it not being flaged for Mac OS X, but it still tries to copy it during the build.

And then the other confusing thing, is that for Windows it seems to put the dll(s) into 2 seperate folders (x86 or x86_64), but on the Mac it just drops them into the root plugin folder. So that is why I'm getting the error, because it's trying to put the 2 different .so files into the root.

Since I'm not targetting x86 builds, I think it is ok for me to just select Exclude platforms 'Standalone' on the x86 libsteam_api and then it doesn't copy that .so 

I still get the x86_64 verion copied on the Mac though, but I guess that will just get ignored, or should I set that to not be 'Mac OS X' also, since Mac wont use that?

Am I right in my thinking?

Any help would be appricated, as I'm a bit unsure here. Thanks.

**Comment by rlabrecque** [comment]
Hey, yeah, sorry about this! This issue looks like a mix between super advanced Unity features, possibly a Unity bug or two, and that Steamworks.NET isn't being helpful here currently.

You can safely disable the .so files from getting copied on OSX for sure. On older versions of Unity Steamworks.NET would manually try to enforce the correct platform settings for the plugins, this was dropped as Unity got better at this in 2018, but seems to have regressed again in 2019.3-4 (possibly for good reasons!)

The real solution will be to ship .meta files along side them which have the platforms already setup. (Though there's a minor lack of clarity over how this works with multiple unity versions.)

The other issue being building on M1 Mac's seems to result in the `steam_api.bundle` getting copied as ARM/M1 native, when it should be set to x86_64. The solution to that should be roughly the same, the settings for the actual plugin need to be updated.

**Comment by RobDonovan** [comment]
Ok great, thnaks for the confirmation @rlabrecque 

Will just disable it for x86 for now, and then look at it again in the future with any new versions that come along.

Thanks for your work with Steamworks.NET.

**Comment by Tanshaydar** [comment]
A quick update on this, I've recently updated to Unity 2019.4 LTS and Steamworks.Net to 15.0.0 and I've started to have this issue on Mac builds.
Windows x86 & x64 and Linux x64 works just fine, however I couldn't take Mac builds.

The issue is libsteam_api.so file is selected for both Linux x64 and Mac x64:
![image](https://user-images.githubusercontent.com/1215477/116424441-3084fc00-a84a-11eb-94b8-881a8e0ef8ab.png)

SteamApi.bundle file is also selected for Mac x64:
![image](https://user-images.githubusercontent.com/1215477/116424530-4397cc00-a84a-11eb-8774-94251e376999.png)

I'm taking multiplatform builds, therefore I need Mac and Linux builds too.
I unchecked the box for libsteam_api.so for Mac and it worked, it took the build. 

Now I don't have a Mac and I'll need one of my friends with a Mac to test it to see if it works runtime. I'll update this when I get the results, but this wasn't an issue before.

Anyway.
Obligatory, great work with Steamworks.net, thanks a lot for bringing this to us!

**Comment by rlabrecque** [comment]
I believe this is fixed as of #414 now, because we include the .meta files to explicitly set this consistently now 🎉

**Comment by Tanshaydar** [comment]
Unfortunately the issue persists.
Unity 2019.4.25f1
Steamworks.NET 15.0.1

I'm currently skipping MAC builds.

**Comment by rlabrecque** [comment]
That change hasn't made it's way into a release yet, will likely take a few weeks.

As of that change Steamworks.NET can now be installed from the Unity Package Manager though!

https://github.com/rlabrecque/Steamworks.NET/issues/389#issuecomment-830982635
